### ISSUE TITLE
Empty output array

### ISSUE THREAD

**Issue by 07freedom** [nihui/ncnn-webassembly-nanodet#10]
[new commit](https://github.com/07freedom/ncnn-webassembly-nanodet/commit/43a16a323c8084a545aabda943a36275bb76cc26)
I have been trying to add detection results as another output but failed with empty array...
I followed your instructions:[跑在浏览器里的ncnn和webassembly - nihui的文章 - 知乎](https://zhuanlan.zhihu.com/p/305601273)
What went wrong?

**Comment by 07freedom** [comment]
@nihui 麻烦大佬帮看一眼，结果全是0，图片结果也不对了

**Comment by 07freedom** [comment]
test passed

**Comment by xiang-wuu** [comment]
@07freedom hi, i am also getting empty array by trying your [private fork](https://github.com/07freedom/ncnn-webassembly-nanodet/commit/43a16a323c8084a545aabda943a36275bb76cc26), any help on how you resolved it.
